# Generated by Django 5.1.6 on 2025-02-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.pod'),
        ),
    ]
