# Generated by Django 5.1.5 on 2025-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_payment_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='podbooking',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='podbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
