# Generated by Django 5.1.6 on 2025-02-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_podbooking_hours_podbooking_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='podbooking',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_bookings_v1', to='home.pod'),
        ),
        migrations.AlterField(
            model_name='podbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings_v1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_type', models.CharField(choices=[('Pre Paid', 'Pre Paid'), ('Post Paid', 'Post Paid')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_bookings_v2', to='home.pod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings_v2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
