# Generated by Django 5.1.6 on 2025-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_podbooking_pod_alter_podbooking_user_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='podbooking',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
