# Generated by Django 5.1.6 on 2025-02-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_podbooking_calendar_event_id'),
        ('home', '0012_alter_payment_options_payment_booking_and_more'),
    ]

    operations = [
    ]
