# Generated by Django 5.1.5 on 2025-02-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20250209_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
