# Generated by Django 5.1.5 on 2025-02-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_payment_options_remove_payment_booking_and_more'),
        ('home', '0015_payment'),
    ]

    operations = [
    ]
