# Generated by Django 5.1.6 on 2025-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_amenity_remove_payment_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='podbooking',
            name='check_in_time',
            field=models.CharField(default='14:00', max_length=5),
        ),
    ]
