# Generated by Django 5.1.6 on 2025-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_payment_options_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
